"""Writes a MODTRAN-tape7-shaped text file from synthetic spectral arrays.

Column order and header-label text match the real IEMSCT=2 layout that
src/radiant/atmosphere/modtran.py's Tape7Reader (CU-066) parses by
label. Every file carries a loud SYNTHETIC banner so it is never
mistaken for real MODTRAN output.
"""

from __future__ import annotations

from pathlib import Path

import numpy as np

_BANNER = """\
================================================================================
 SYNTHETIC TAPE7 -- NOT REAL MODTRAN OUTPUT
 Generated by scripts/generate_synthetic_tape7.py from
 docs/plans/modtran_run_matrix.csv. Molecular transmittance (TOT TRANS)
 and thermal path radiance (PTH THRML) are computed from real HITRAN
 line-by-line data via RADIS on an independently-built layered
 atmosphere -- NOT derived from RADIANT's own atmosphere model. SOL
 SCAT / SNGL SCAT are a simplified single-scatter estimate, NOT
 multiple-scattering DISORT -- do not treat as MODTRAN-equivalent.
 GRND RFLT / DRCT RFLT / SURF EMIS / THRML SCT are 0 (unmodeled; every
 run in the matrix has surface_albedo_surref = 0). See
 modtran/synthetic/README.md for the full caveat list.
================================================================================
"""

_HEADER_LINE = (
    "   FREQ   TOT TRANS   PTH THRML   THRML SCT   SURF EMIS   "
    "SOL SCAT   SNGL SCAT   GRND RFLT   DRCT RFLT   TOTAL RAD"
)


def write_synthetic_tape7(
    path: Path,
    run_id: str,
    wavenumber_cm1: np.ndarray,
    total_transmittance: np.ndarray,
    path_thermal_radiance: np.ndarray,
    sol_scat_radiance: np.ndarray,
) -> None:
    """Write a descending-wavenumber, name-headered synthetic tape7.

    ``THRML SCT``, ``SURF EMIS``, ``GRND RFLT``, ``DRCT RFLT`` are
    written as 0 (unmodeled). ``SNGL SCAT`` is set equal to
    ``sol_scat_radiance`` (the single-scatter estimate has no separate
    multiple-scatter component to subtract). ``TOTAL RAD`` is the sum
    of the nonzero radiance columns.
    """
    order = np.argsort(wavenumber_cm1)[::-1]  # descending, MODTRAN convention
    nu = wavenumber_cm1[order]
    trans = total_transmittance[order]
    pth_thrml = path_thermal_radiance[order]
    sol_scat = sol_scat_radiance[order]
    zero = np.zeros_like(nu)
    total_rad = pth_thrml + sol_scat

    lines = [_BANNER, f" RUN: {run_id}", "", _HEADER_LINE]
    for i in range(len(nu)):
        lines.append(
            f"{nu[i]:12.4f}{trans[i]:12.6f}{pth_thrml[i]:12.4e}"
            f"{zero[i]:12.4e}{zero[i]:12.4e}{sol_scat[i]:12.4e}"
            f"{sol_scat[i]:12.4e}{zero[i]:12.4e}{zero[i]:12.4e}"
            f"{total_rad[i]:12.4e}"
        )
    path.write_text("\n".join(lines) + "\n", encoding="utf-8", newline="\n")
