"""Tests for the Zemax "Zernike Standard Coefficients" importer.

Level 0: the parsed coefficient dicts are asserted against hand-transcribed
values from the committed fixture files (written by hand, not by RADIANT).

Fixtures (src/radiant/io/tests/fixtures/):
    zernike_standard_utf8.txt         — realistic UTF-8 export, 8 terms
    zernike_standard_utf16le_bom.txt  — UTF-16-LE with BOM (generated by
                                        fixtures/make_utf16_fixture.py)
    zernike_malformed_no_terms.txt    — header only, no Z lines
"""

from __future__ import annotations

import codecs
from pathlib import Path

import pytest

from radiant.core.exceptions import RadiantError
from radiant.io.zemax_zernike import (
    ZemaxParseError,
    ZemaxZernikeResult,
    load_zemax_zernike,
)
from radiant.optics.wavefront import WavefrontError, WfeMode

FIXTURES = Path(__file__).parent / "fixtures"

# Hand-transcribed from zernike_standard_utf8.txt (Level 0 truth values).
UTF8_EXPECTED: dict[int, float] = {
    1: 0.12345678,
    2: -0.00234567,
    3: 0.01000000,
    4: 0.05500000,
    5: -0.00012345,
    6: 1.2500e-03,
    7: 0.00000000,
    8: -0.02750000,
}
UTF8_WAVELENGTH_UM = 4.0

# Hand-transcribed from zernike_standard_utf16le_bom.txt.
UTF16_EXPECTED: dict[int, float] = {
    1: 0.00000000,
    2: 0.10000000,
    3: -0.05000000,
    4: 0.02500000,
}
UTF16_WAVELENGTH_UM = 0.6328


class TestLevel0Parsing:
    """Parsed values match the fixture file exactly (hand values)."""

    def test_utf8_coefficients_exact(self) -> None:
        result = load_zemax_zernike(FIXTURES / "zernike_standard_utf8.txt")
        assert set(result.zernike_coeffs.keys()) == set(UTF8_EXPECTED.keys())
        for j, expected in UTF8_EXPECTED.items():
            assert result.zernike_coeffs[j] == pytest.approx(expected, abs=1e-12)

    def test_utf8_wavelength_extraction(self) -> None:
        result = load_zemax_zernike(FIXTURES / "zernike_standard_utf8.txt")
        assert result.reference_wavelength_um == pytest.approx(UTF8_WAVELENGTH_UM, abs=1e-12)

    def test_utf8_n_terms_and_source_file(self) -> None:
        path = FIXTURES / "zernike_standard_utf8.txt"
        result = load_zemax_zernike(path)
        assert result.n_terms == 8
        assert result.source_file == str(path)

    def test_piston_z1_is_included(self) -> None:
        """Z1 (piston) is parsed and kept — downstream decides what to drop."""
        result = load_zemax_zernike(FIXTURES / "zernike_standard_utf8.txt")
        assert 1 in result.zernike_coeffs
        assert result.zernike_coeffs[1] == pytest.approx(0.12345678, abs=1e-12)

    def test_trailing_polynomial_formula_ignored(self) -> None:
        """Real exports append ':  4^(1/2) (p) * COS (A)' etc. after the value."""
        result = load_zemax_zernike(FIXTURES / "zernike_standard_utf8.txt")
        assert result.zernike_coeffs[2] == pytest.approx(-0.00234567, abs=1e-12)

    def test_scientific_notation_coefficient(self) -> None:
        result = load_zemax_zernike(FIXTURES / "zernike_standard_utf8.txt")
        assert result.zernike_coeffs[6] == pytest.approx(1.2500e-03, abs=1e-15)

    def test_compact_z_index_form(self, tmp_path: Path) -> None:
        """Some Zemax versions emit 'Z4' with no space before the index."""
        f = tmp_path / "compact.txt"
        f.write_text(
            "Zernike Standard Coefficients\n"
            "Wavelength : 3.5000 µm\n"
            "Z1   0.10000000\n"
            "Z2  -0.20000000\n",
            encoding="utf-8",
        )
        result = load_zemax_zernike(f)
        assert result.zernike_coeffs[1] == pytest.approx(0.1, abs=1e-12)
        assert result.zernike_coeffs[2] == pytest.approx(-0.2, abs=1e-12)

    def test_wavelength_missing_gives_none(self, tmp_path: Path) -> None:
        f = tmp_path / "no_wavelength.txt"
        f.write_text("Z   1      0.50000000\n", encoding="utf-8")
        result = load_zemax_zernike(f)
        assert result.reference_wavelength_um is None
        assert result.zernike_coeffs[1] == pytest.approx(0.5, abs=1e-12)


class TestEncodings:
    """UTF-8, UTF-16 (with and without BOM), and latin-1 fallback."""

    def test_utf16le_bom_fixture(self) -> None:
        result = load_zemax_zernike(FIXTURES / "zernike_standard_utf16le_bom.txt")
        assert set(result.zernike_coeffs.keys()) == set(UTF16_EXPECTED.keys())
        for j, expected in UTF16_EXPECTED.items():
            assert result.zernike_coeffs[j] == pytest.approx(expected, abs=1e-12)
        assert result.reference_wavelength_um == pytest.approx(UTF16_WAVELENGTH_UM, abs=1e-12)

    def test_utf16le_fixture_really_has_bom(self) -> None:
        raw = (FIXTURES / "zernike_standard_utf16le_bom.txt").read_bytes()
        assert raw.startswith(codecs.BOM_UTF16_LE)

    def test_utf16be_bom(self, tmp_path: Path) -> None:
        text = "Wavelength : 2.2000 µm\nZ   1      0.30000000\n"
        f = tmp_path / "utf16be.txt"
        f.write_bytes(codecs.BOM_UTF16_BE + text.encode("utf-16-be"))
        result = load_zemax_zernike(f)
        assert result.zernike_coeffs[1] == pytest.approx(0.3, abs=1e-12)
        assert result.reference_wavelength_um == pytest.approx(2.2, abs=1e-12)

    def test_utf16le_without_bom(self, tmp_path: Path) -> None:
        """Some Zemax exports are BOM-less UTF-16-LE; detected via NUL bytes."""
        text = "Wavelength : 1.0640 µm\nZ   1     -0.07500000\n"
        f = tmp_path / "utf16le_nobom.txt"
        f.write_bytes(text.encode("utf-16-le"))
        result = load_zemax_zernike(f)
        assert result.zernike_coeffs[1] == pytest.approx(-0.075, abs=1e-12)
        assert result.reference_wavelength_um == pytest.approx(1.064, abs=1e-12)

    def test_utf8_with_bom(self, tmp_path: Path) -> None:
        text = "Wavelength : 0.5500 µm\nZ   1      0.01000000\n"
        f = tmp_path / "utf8_bom.txt"
        f.write_bytes(codecs.BOM_UTF8 + text.encode("utf-8"))
        result = load_zemax_zernike(f)
        assert result.zernike_coeffs[1] == pytest.approx(0.01, abs=1e-12)
        assert result.reference_wavelength_um == pytest.approx(0.55, abs=1e-12)

    def test_latin1_fallback(self, tmp_path: Path) -> None:
        """0xB5 ('µ' in latin-1) is invalid as a UTF-8 lead byte."""
        f = tmp_path / "latin1.txt"
        f.write_bytes(b"Wavelength : 3.8000 \xb5m\nZ   1      0.20000000\n")
        result = load_zemax_zernike(f)
        assert result.zernike_coeffs[1] == pytest.approx(0.2, abs=1e-12)
        assert result.reference_wavelength_um == pytest.approx(3.8, abs=1e-12)


class TestToWavefrontError:
    """Round-trip into the Gap 24/25 Zernike pipeline."""

    def test_round_trip_mode_coeffs_wavelength(self) -> None:
        result = load_zemax_zernike(FIXTURES / "zernike_standard_utf8.txt")
        wfe = result.to_wavefront_error()
        assert isinstance(wfe, WavefrontError)
        assert wfe.mode == WfeMode.ZERNIKE
        assert wfe.zernike_coeffs is not None
        assert set(wfe.zernike_coeffs.keys()) == set(UTF8_EXPECTED.keys())
        for j, expected in UTF8_EXPECTED.items():
            assert wfe.zernike_coeffs[j] == pytest.approx(expected, abs=1e-12)
        assert wfe.reference_wavelength_um == pytest.approx(UTF8_WAVELENGTH_UM, abs=1e-12)

    def test_explicit_wavelength_override(self) -> None:
        result = load_zemax_zernike(FIXTURES / "zernike_standard_utf8.txt")
        wfe = result.to_wavefront_error(reference_wavelength_um=0.633)
        assert wfe.reference_wavelength_um == pytest.approx(0.633, abs=1e-12)

    def test_no_wavelength_anywhere_raises(self, tmp_path: Path) -> None:
        f = tmp_path / "no_wavelength.txt"
        f.write_text("Z   1      0.50000000\n", encoding="utf-8")
        result = load_zemax_zernike(f)
        with pytest.raises(ZemaxParseError, match="reference_wavelength_um"):
            result.to_wavefront_error()

    def test_coeff_dict_is_a_copy(self) -> None:
        """Mutating the WavefrontError dict must not alias the result dict."""
        result = load_zemax_zernike(FIXTURES / "zernike_standard_utf8.txt")
        wfe = result.to_wavefront_error()
        assert wfe.zernike_coeffs is not None
        assert wfe.zernike_coeffs is not result.zernike_coeffs


class TestErrors:
    """Actionable ZemaxParseError on every failure path (Rule 15)."""

    def test_error_is_radiant_error(self) -> None:
        assert issubclass(ZemaxParseError, RadiantError)

    def test_malformed_no_z_lines(self) -> None:
        with pytest.raises(ZemaxParseError) as excinfo:
            load_zemax_zernike(FIXTURES / "zernike_malformed_no_terms.txt")
        # Actionable payload present.
        assert excinfo.value.what
        assert excinfo.value.action
        assert "Z" in str(excinfo.value)

    def test_missing_file(self, tmp_path: Path) -> None:
        with pytest.raises(ZemaxParseError, match="does not exist"):
            load_zemax_zernike(tmp_path / "nonexistent.txt")

    def test_zero_noll_index_rejected(self, tmp_path: Path) -> None:
        f = tmp_path / "z0.txt"
        f.write_text("Z   0      0.10000000\nZ   1      0.20000000\n", encoding="utf-8")
        with pytest.raises(ZemaxParseError, match="Noll"):
            load_zemax_zernike(f)

    def test_duplicate_noll_index_rejected(self, tmp_path: Path) -> None:
        f = tmp_path / "dup.txt"
        f.write_text("Z   4      0.10000000\nZ   4      0.20000000\n", encoding="utf-8")
        with pytest.raises(ZemaxParseError, match="[Dd]uplicate"):
            load_zemax_zernike(f)

    def test_nonfinite_coefficient_rejected(self, tmp_path: Path) -> None:
        """1e999 overflows float to inf — must be caught, not propagated."""
        f = tmp_path / "inf.txt"
        f.write_text("Z   4      1e999\n", encoding="utf-8")
        with pytest.raises(ZemaxParseError, match="finite"):
            load_zemax_zernike(f)

    def test_nonpositive_wavelength_rejected(self, tmp_path: Path) -> None:
        f = tmp_path / "badwl.txt"
        f.write_text("Wavelength : 0.0000 µm\nZ   1      0.10000000\n", encoding="utf-8")
        with pytest.raises(ZemaxParseError, match="[Ww]avelength"):
            load_zemax_zernike(f)

    def test_empty_file(self, tmp_path: Path) -> None:
        f = tmp_path / "empty.txt"
        f.write_text("", encoding="utf-8")
        with pytest.raises(ZemaxParseError):
            load_zemax_zernike(f)


class TestResultDataclass:
    def test_frozen(self) -> None:
        result = ZemaxZernikeResult(
            zernike_coeffs={4: 0.05},
            reference_wavelength_um=1.0,
            n_terms=1,
            source_file="x.txt",
        )
        with pytest.raises(AttributeError):
            result.n_terms = 2  # type: ignore[misc]
